name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v2'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}
          credentials_json: ${{ secrets.CLOUD_RUN_SERVICE_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # - name: Build and push container image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: backend
      #     push: true
      #     tags: gcr.io/${{ secrets.CLOUD_RUN_PROJECT_ID }}/backend:latest

      # - name: Deploy to Cloud Run
      #   uses: GoogleCloudPlatform/github-actions/cloud-run@master
      #   with:
      #     service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}
      #     project_id: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
      #     region: ${{ secrets.CLOUD_RUN_REGION }}
      #     service_name: backend
      #     image_name: backend
      #     tag: latest
      #     platform: managed
